# Generated by Django 5.1.5 on 2025-02-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_type', models.CharField(max_length=100)),
                ('recruitment_start', models.DateField()),
                ('recruitment_end', models.DateField()),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('product_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('selection_method_details', models.TextField(blank=True, null=True)),
                ('number_of_recipients_details', models.TextField(blank=True, null=True)),
                ('grade_criteria_details', models.TextField(blank=True, null=True)),
                ('income_criteria_details', models.TextField(blank=True, null=True)),
                ('managing_organization_type', models.CharField(blank=True, max_length=255, null=True)),
                ('foundation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('eligibility_restrictions', models.TextField(blank=True, null=True)),
                ('required_documents_details', models.TextField(blank=True, null=True)),
                ('residency_requirement_details', models.TextField(blank=True, null=True)),
                ('support_details', models.TextField(blank=True, null=True)),
                ('recommendation_required', models.BooleanField(default=False)),
                ('specific_qualification_details', models.TextField(blank=True, null=True)),
                ('major_field_type', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
