# Generated by Django 5.1.5 on 2025-02-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_emailverification_profile_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
