# Generated by Django 5.1.7 on 2025-06-10 06:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name': '장학금', 'verbose_name_plural': '장학금 목록'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': '찜 목록', 'verbose_name_plural': '찜 목록'},
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='academic_year_type',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='major_field_type',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='recruitment_end',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='recruitment_start',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='academic_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='학년 구분'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='major_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='학과 구분'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='recruitment_end_date',
            field=models.DateField(default=datetime.date(2099, 12, 31), verbose_name='모집 종료일'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='recruitment_start_date',
            field=models.DateField(default=datetime.date(2099, 12, 31), verbose_name='모집 시작일'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지역 조건'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility_restrictions',
            field=models.TextField(blank=True, null=True, verbose_name='자격 제한'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='foundation_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='운영 기관 이름'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='grade_criteria_details',
            field=models.TextField(blank=True, null=True, verbose_name='성적 기준 상세'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='income_criteria_details',
            field=models.TextField(blank=True, null=True, verbose_name='소득 기준 상세'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='managing_organization_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='운영 기관 구분'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='name',
            field=models.CharField(max_length=255, verbose_name='장학금 이름'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='number_of_recipients_details',
            field=models.TextField(blank=True, null=True, verbose_name='선발 인원 상세'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='product_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='고유 번호'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='product_type',
            field=models.CharField(max_length=100, verbose_name='장학금 유형'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='recommendation_required',
            field=models.BooleanField(default=False, verbose_name='추천서 필요 여부'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='required_documents_details',
            field=models.TextField(blank=True, null=True, verbose_name='제출 서류 상세'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='residency_requirement_details',
            field=models.TextField(blank=True, null=True, verbose_name='지역 조건 상세'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='selection_method_details',
            field=models.TextField(blank=True, null=True, verbose_name='선발 기준 및 절차'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='specific_qualification_details',
            field=models.TextField(blank=True, null=True, verbose_name='특정 자격 조건 상세'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='support_details',
            field=models.TextField(blank=True, null=True, verbose_name='지원금액 상세'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='university_type',
            field=models.CharField(max_length=100, verbose_name='대학 유형'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='추가일'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.scholarship', verbose_name='장학금'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
