# Generated by Django 5.1.7 on 2025-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_alter_scholarship_options_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='academic_year_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='학년 유형'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='recruitment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='모집 종료일'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='recruitment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='모집 시작일'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='university_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대학 유형'),
        ),
    ]
