# Generated by Django 5.1.7 on 2025-06-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_remove_scholarship_academic_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='recruitment_end_date',
            new_name='recruitment_end',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='recruitment_start_date',
            new_name='recruitment_start',
        ),
    ]
