# Generated by Django 5.1.7 on 2025-06-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_rename_recruitment_end_date_scholarship_recruitment_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='region',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='is_region_processed',
            field=models.BooleanField(default=False, help_text='지역 정보 전처리 완료 여부'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='regions',
            field=models.CharField(blank=True, help_text='전처리된 지역 정보 (쉼표로 구분)', max_length=512),
        ),
    ]
