# Generated by Django 5.1.7 on 2025-06-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_remove_scholarship_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='regions',
            new_name='region',
        ),
    ]
