# Generated by Django 5.1.7 on 2025-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_rename_regions_scholarship_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='고유 번호')),
                ('name', models.CharField(max_length=255, verbose_name='장학금 이름')),
                ('product_type', models.CharField(max_length=100, verbose_name='장학금 유형')),
                ('recruitment_start', models.DateField(blank=True, null=True, verbose_name='모집 시작일')),
                ('recruitment_end', models.DateField(blank=True, null=True, verbose_name='모집 종료일')),
                ('university_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='대학 유형')),
                ('academic_year_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='학년 유형')),
                ('major_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='학과 구분')),
                ('residency_requirement_details', models.TextField(blank=True, null=True, verbose_name='지역 조건 상세')),
                ('grade_criteria_details', models.TextField(blank=True, null=True, verbose_name='성적 기준 상세')),
                ('income_criteria_details', models.TextField(blank=True, null=True, verbose_name='소득 기준 상세')),
                ('specific_qualification_details', models.TextField(blank=True, null=True, verbose_name='특정 자격 조건 상세')),
                ('eligibility_restrictions', models.TextField(blank=True, null=True, verbose_name='자격 제한')),
                ('managing_organization_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='운영 기관 구분')),
                ('foundation_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='운영 기관 이름')),
                ('selection_method_details', models.TextField(blank=True, null=True, verbose_name='선발 기준 및 절차')),
                ('number_of_recipients_details', models.TextField(blank=True, null=True, verbose_name='선발 인원 상세')),
                ('required_documents_details', models.TextField(blank=True, null=True, verbose_name='제출 서류 상세')),
                ('support_details', models.TextField(blank=True, null=True, verbose_name='지원금액 상세')),
                ('recommendation_required', models.BooleanField(default=False, verbose_name='추천서 필요 여부')),
            ],
            options={
                'verbose_name': '원본 장학금',
                'verbose_name_plural': '원본 장학금 목록',
            },
        ),
    ]
