# Generated by Django 5.1.7 on 2025-08-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0010_rawscholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawscholarship',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='홈페이지 주소'),
        ),
    ]
