# Generated by Django 5.1.7 on 2025-09-08 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['conversation', '-created_at'], name='community_d_convers_0981ee_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['conversation', 'is_read'], name='community_d_convers_a8e9e4_idx'),
        ),
    ]
