# Generated by Django 5.1.5 on 2025-02-12 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScholarship',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('income_level', models.CharField(blank=True, max_length=50, null=True)),
                ('university_category', models.CharField(blank=True, max_length=50, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('gpa_last', models.FloatField(blank=True, null=True)),
                ('gpa_total', models.FloatField(blank=True, null=True)),
                ('multi_culture_family', models.BooleanField(default=False)),
                ('single_parent_family', models.BooleanField(default=False)),
                ('multiple_children_family', models.BooleanField(default=False)),
                ('national_merit', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
