# Generated by Django 5.1.7 on 2025-06-10 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscholarship',
            options={'verbose_name': '사용자 장학 정보', 'verbose_name_plural': '사용자 장학 정보 목록'},
        ),
        migrations.RemoveField(
            model_name='userscholarship',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userscholarship',
            name='gpa_last',
        ),
        migrations.RemoveField(
            model_name='userscholarship',
            name='gpa_total',
        ),
        migrations.RemoveField(
            model_name='userscholarship',
            name='multi_culture_family',
        ),
        migrations.RemoveField(
            model_name='userscholarship',
            name='multiple_children_family',
        ),
        migrations.RemoveField(
            model_name='userscholarship',
            name='national_merit',
        ),
        migrations.RemoveField(
            model_name='userscholarship',
            name='single_parent_family',
        ),
        migrations.RemoveField(
            model_name='userscholarship',
            name='university',
        ),
        migrations.RemoveField(
            model_name='userscholarship',
            name='university_category',
        ),
        migrations.AddField(
            model_name='userscholarship',
            name='gpa_last_semester',
            field=models.FloatField(blank=True, null=True, verbose_name='직전 학기 평점'),
        ),
        migrations.AddField(
            model_name='userscholarship',
            name='gpa_overall',
            field=models.FloatField(blank=True, null=True, verbose_name='전체 학기 평점'),
        ),
        migrations.AddField(
            model_name='userscholarship',
            name='is_multi_cultural_family',
            field=models.BooleanField(default=False, verbose_name='다문화 가정 여부'),
        ),
        migrations.AddField(
            model_name='userscholarship',
            name='is_multiple_children_family',
            field=models.BooleanField(default=False, verbose_name='다자녀 가정 여부'),
        ),
        migrations.AddField(
            model_name='userscholarship',
            name='is_national_merit',
            field=models.BooleanField(default=False, verbose_name='국가유공자 여부'),
        ),
        migrations.AddField(
            model_name='userscholarship',
            name='is_single_parent_family',
            field=models.BooleanField(default=False, verbose_name='한부모 가정 여부'),
        ),
        migrations.AddField(
            model_name='userscholarship',
            name='major_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='학과명'),
        ),
        migrations.AddField(
            model_name='userscholarship',
            name='university_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='학교명'),
        ),
        migrations.AddField(
            model_name='userscholarship',
            name='university_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='대학 유형'),
        ),
        migrations.AlterField(
            model_name='userscholarship',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='userscholarship',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='추가 정보'),
        ),
        migrations.AlterField(
            model_name='userscholarship',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='userscholarship',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='시/군/구'),
        ),
        migrations.AlterField(
            model_name='userscholarship',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='userscholarship',
            name='income_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='소득 분위'),
        ),
        migrations.AlterField(
            model_name='userscholarship',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='userscholarship',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='시/도'),
        ),
        migrations.AlterField(
            model_name='userscholarship',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='학기'),
        ),
        migrations.AlterField(
            model_name='userscholarship',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
