# Generated by Django 5.1.7 on 2025-06-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfor', '0002_alter_userscholarship_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscholarship',
            old_name='academic_year',
            new_name='academic_year_type',
        ),
    ]
