# Generated by Django 5.1.7 on 2025-07-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfor', '0003_rename_academic_year_userscholarship_academic_year_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscholarship',
            name='major_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='학과'),
        ),
    ]
